In [2]:
import pandas as pd

In [2]:
sales = pd.read_csv('data/ShopriteData/STB CompSci Hons Project - sales data.csv')

In [10]:
sales.head()

,date_key,site_code,unique_ticket_id,ticket_end_time,article_code,sales_qty_alternate_uom,alternate_uom,sales_qty_base_uom,base_uom
0,20220103,236,8d379521-cf90-4d83-8d8b-a2c001313b88,2022-01-03 08:02:03.000,10730757,1.0,EA,1.0,EA
1,20220103,236,aea5b653-2751-489e-b98c-9141d84c7018,2022-01-03 08:04:36.000,10665601,1.0,EA,1.0,EA
2,20220103,236,c6b2b8c8-1b52-4375-b065-79e48933fab6,2022-01-03 08:09:12.000,10164184,1.0,EA,1.0,EA
3,20220103,236,45bc7474-a244-4c5a-b5c1-584f8662d1f2,2022-01-03 08:09:43.000,10722932,1.0,EA,1.0,EA
4,20220103,236,150a9040-fb3b-4b4e-9170-17d8af09e725,2022-01-03 08:09:59.000,10143154,1.0,EA,1.0,EA

In [12]:
print(sales.shape)
print(sales.columns)

(12570509, 9)
Index(['date_key', 'site_code', 'unique_ticket_id', 'ticket_end_time',
       'article_code', 'sales_qty_alternate_uom', 'alternate_uom',
       'sales_qty_base_uom', 'base_uom'],
      dtype='object')

In [16]:
articles = pd.read_csv('data/ShopriteData/STB CompSci Hons Project - article data.csv')
articles.head()

,article_code,article_desc,base_uom,super_dept_no,super_dept_desc,dept_no,dept_desc,category_no,category_desc,merchandise_category_no,merchandise_category_desc,sub_category_no,sub_category_desc
0,10129768,PETER STUY BLUE 30S PACK,EA,10,General Groceries,1031,Cigarettes and Tobacco,103101,Cigarettes and Tobacco,10310101,Cigarettes,1.031010e+09,SINGLES 30'S
1,10129769,PETER STUY FILTER LAUBE 30S PACK,EA,10,General Groceries,1031,Cigarettes and Tobacco,103101,Cigarettes and Tobacco,10310101,Cigarettes,1.031010e+09,SINGLES 30'S
2,10124712,CHESTERFIELD CLASSIC BLUE 20S PACK,EA,10,General Groceries,1031,Cigarettes and Tobacco,103101,Cigarettes and Tobacco,10310101,Cigarettes,1.031010e+09,SINGLES 20'S
3,10129599,"EMBASSY 20S, NATURAL",EA,10,General Groceries,1031,Cigarettes and Tobacco,103101,Cigarettes and Tobacco,10310101,Cigarettes,1.031010e+09,SINGLES 20'S
4,10129704,CAMEL REG SOFT 10X20S,EA,10,General Groceries,1031,Cigarettes and Tobacco,103101,Cigarettes and Tobacco,10310101,Cigarettes,1.031010e+09,SINGLES 20'S

In [17]:
print(articles.shape)
print(articles.columns)

(17903, 13)
Index(['article_code', 'article_desc', 'base_uom', 'super_dept_no',
       'super_dept_desc', 'dept_no', 'dept_desc', 'category_no',
       'category_desc', 'merchandise_category_no', 'merchandise_category_desc',
       'sub_category_no', 'sub_category_desc'],
      dtype='object')

In [3]:
movement = pd.read_csv('data/ShopriteData/STB CompSci Hons Project - movements data.csv')
movement.head()

/var/folders/2n/nk_kz9ln5yn5w2l0d_6mznh40000gn/T/ipykernel_16312/3989930233.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  movement = pd.read_csv('data/ShopriteData/STB CompSci Hons Project - movements data.csv')

,unique_key,posting_date,entry_timestamp,site_code,article_code,movement_type,movement_type_category,quantity_base_uom,base_uom,stock_level_before_posting
0,2023-3356087075-0001,20230714,2023-07-14 22:33:36.000,236,10100035,251,Sales,-1.0,EA,15.0
1,2023-3357353385-0001,20230719,2023-07-19 22:03:53.000,236,10100035,251,Sales,-1.0,EA,14.0
2,2023-3365441961-0001,20230818,2023-08-18 23:01:31.000,236,10100035,251,Sales,-1.0,EA,13.0
3,2023-3370931458-0001,20230906,2023-09-06 22:48:45.000,236,10100035,251,Sales,-1.0,EA,12.0
4,2023-3376287420-0001,20230924,2023-09-26 08:55:42.000,236,10100035,702,Shrinkage,-4.0,EA,11.0

In [5]:
len(movement)

1094999

In [14]:
print(movement["movement_type"].unique())

[251 702 101 252 701 551 943 161 901 309 552 310 102 162 '251' '101' '551'
 '701' '702' '252' '901' '309' '310' '943' '161' 'Y51' 'Y52' '102' '552'
 '162' 643]

In [16]:
import pandas as pd

# Assuming 'movement' is your DataFrame
# Print unique movement_types
print(movement["movement_type"].unique())

# Loop through each unique movement type and print a sample from the DataFrame
for movement_type in movement["movement_type"].unique():
    # Filter the DataFrame for the current movement type
    filtered_data = movement[movement["movement_type"] == movement_type]
    
    # Print a sample entry; adjust n=1 to change the number of samples
    print(f"Sample for movement_type {movement_type}:")
    print(filtered_data.sample(n=1))

[251 702 101 252 701 551 943 161 901 309 552 310 102 162 '251' '101' '551'
 '701' '702' '252' '901' '309' '310' '943' '161' 'Y51' 'Y52' '102' '552'
 '162' 643]
Sample for movement_type 251:
                  unique_key  posting_date          entry_timestamp  \
498779  2023-3394610908-0192      20231129  2023-11-29 22:43:24.000

        article_code movement_type movement_type_category  quantity_base_uom  \
498779      10250929           251                  Sales               -1.0

       base_uom  stock_level_before_posting
498779       EA                         4.0
Sample for movement_type 702:
                  unique_key  posting_date          entry_timestamp  \
574298  2023-3376287284-0090      20230924  2023-09-26 08:53:06.000

        article_code movement_type movement_type_category  quantity_base_uom  \
574298      10368682           702              Shrinkage               -1.0

       base_uom  stock_level_before_posting
574298       EA                        27.0
Sample for movement_type 101:
                  unique_key  posting_date          entry_timestamp  \
108296  2023-5134099009-0045      20231215  2023-12-15 05:22:09.000

        article_code movement_type movement_type_category  quantity_base_uom  \
108296      10129836           101          Goods Receipt               60.0

       base_uom  stock_level_before_posting
108296       EA                        13.0
Sample for movement_type 252:
                  unique_key  posting_date          entry_timestamp  \
119855  2023-3361943716-0035      20230805  2023-08-05 22:39:24.000

        article_code movement_type movement_type_category  quantity_base_uom  \
119855      10130873           252                  Sales                2.0

       base_uom  stock_level_before_posting
119855       EA                        51.0
Sample for movement_type 701:
                 unique_key  posting_date          entry_timestamp  \
84997  2023-3401188711-0001      20231221  2023-12-22 00:27:06.000

       article_code movement_type movement_type_category  quantity_base_uom  \
84997      10127570           701              Shrinkage                1.0

      base_uom  stock_level_before_posting
84997       EA                        34.0
Sample for movement_type 551:
                  unique_key  posting_date          entry_timestamp  \
988648  2023-3380324794-0013      20231010  2023-10-10 15:46:49.000

        article_code movement_type movement_type_category  quantity_base_uom  \
988648      10741526           551  Wastage and Donations               -3.0

       base_uom  stock_level_before_posting
988648       EA                       342.0
Sample for movement_type 943:
                 unique_key  posting_date          entry_timestamp  \
39107  2023-3400476146-0010      20231219  2023-12-19 15:12:07.000

       article_code movement_type movement_type_category  quantity_base_uom  \
39107      10124088           943                  Other              -10.0

      base_uom  stock_level_before_posting
39107       EA                       359.0
Sample for movement_type 161:
                  unique_key  posting_date          entry_timestamp  \
431522  2023-5125495308-0005      20230816  2023-08-16 11:41:58.000

        article_code movement_type movement_type_category  quantity_base_uom  \
431522      10211519           161         Vendor Returns               -1.0

       base_uom  stock_level_before_posting
431522       EA                        14.0
Sample for movement_type 901:
                  unique_key  posting_date          entry_timestamp  \
435150  2024-3425459925-0050      20240314  2024-03-14 16:31:11.000

        article_code movement_type movement_type_category  quantity_base_uom  \
435150      10213205           901  Wastage and Donations               -1.0

       base_uom  stock_level_before_posting
435150       EA                        43.0
Sample for movement_type 309:
                  unique_key  posting_date          entry_timestamp  \
110350  2023-3360779233-0005      20230801  2023-08-01 16:04:23.000

        article_code movement_type      movement_type_category  \
110350      10130016           309  Inter-department Transfers

        quantity_base_uom base_uom  stock_level_before_posting
110350               -1.0       EA                       101.0
Sample for movement_type 552:
                  unique_key  posting_date          entry_timestamp  \
787778  2023-3376024151-0001      20230925  2023-09-25 11:59:05.000

        article_code movement_type movement_type_category  quantity_base_uom  \
787778      10538725           552  Wastage and Donations                1.0

       base_uom  stock_level_before_posting
787778       EA                      -0.878
Sample for movement_type 310:
                  unique_key  posting_date          entry_timestamp  \
575927  2024-3407852116-0001      20240114  2024-01-14 08:51:18.000

        article_code movement_type      movement_type_category  \
575927      10369147           310  Inter-department Transfers

        quantity_base_uom base_uom  stock_level_before_posting
575927                1.0       EA                        23.0
Sample for movement_type 102:
                   unique_key  posting_date          entry_timestamp  \
1008045  2024-5138140378-0001      20240212  2024-02-12 15:20:18.000

         article_code movement_type movement_type_category  quantity_base_uom  \
1008045      10762480           102          Goods Receipt               -7.0

        base_uom  stock_level_before_posting
1008045       EA                        11.0
Sample for movement_type 162:
                 unique_key  posting_date          entry_timestamp  \
87130  2024-5138825197-0011      20240222  2024-02-22 08:02:39.000

       article_code movement_type movement_type_category  quantity_base_uom  \
87130      10127804           162         Vendor Returns                6.0

      base_uom  stock_level_before_posting
87130       EA                         9.0
Sample for movement_type 251:
                  unique_key  posting_date          entry_timestamp  \
203218  2023-3390584123-0067      20231115  2023-11-15 22:00:19.000

        article_code movement_type movement_type_category  quantity_base_uom  \
203218      10140398           251                  Sales               -1.0

       base_uom  stock_level_before_posting
203218       EA                        73.0
Sample for movement_type 101:
                  unique_key  posting_date          entry_timestamp  \
188990  2023-5124243310-0012      20230727  2023-07-27 16:46:14.000

        article_code movement_type movement_type_category  quantity_base_uom  \
188990      10138904           101          Goods Receipt               25.0

       base_uom  stock_level_before_posting
188990       EA                        99.0
Sample for movement_type 551:
                  unique_key  posting_date          entry_timestamp  \
279509  2024-3404662336-0008      20240103  2024-01-03 11:36:30.000

        article_code movement_type movement_type_category  quantity_base_uom  \
279509      10146194           551  Wastage and Donations             -0.232

       base_uom  stock_level_before_posting
279509       KG                       8.642
Sample for movement_type 701:
                  unique_key  posting_date          entry_timestamp  \
250692  2023-3392060109-0001      20231120  2023-11-21 00:33:08.000

        article_code movement_type movement_type_category  quantity_base_uom  \
250692      10144588           701              Shrinkage                1.0

       base_uom  stock_level_before_posting
250692       EA                        39.0
Sample for movement_type 702:
                  unique_key  posting_date          entry_timestamp  \
263552  2023-3384589221-0001      20231025  2023-10-26 02:58:11.000

        article_code movement_type movement_type_category  quantity_base_uom  \
263552      10145186           702              Shrinkage               -3.0

       base_uom  stock_level_before_posting
263552       EA                       215.0
Sample for movement_type 252:
                  unique_key  posting_date          entry_timestamp  \
707689  2024-3428871603-0297      20240326  2024-03-26 22:03:21.000

        article_code movement_type movement_type_category  quantity_base_uom  \
707689      10492347           252                  Sales                1.0

       base_uom  stock_level_before_posting
707689       EA                        56.0
Sample for movement_type 901:
                  unique_key  posting_date          entry_timestamp  \
201865  2024-3417224305-0017      20240215  2024-02-15 11:16:35.000

        article_code movement_type movement_type_category  quantity_base_uom  \
201865      10140299           901  Wastage and Donations               -1.0

       base_uom  stock_level_before_posting
201865       EA                       102.0
Sample for movement_type 309:
                  unique_key  posting_date          entry_timestamp  \
903722  2023-3396945593-0001      20231207  2023-12-07 10:16:44.000

        article_code movement_type      movement_type_category  \
903722      10684677           309  Inter-department Transfers

        quantity_base_uom base_uom  stock_level_before_posting
903722               -2.0       EA                        70.0
Sample for movement_type 310:
                  unique_key  posting_date          entry_timestamp  \
904020  2024-3419540724-0001      20240223  2024-02-23 14:32:07.000

        article_code movement_type      movement_type_category  \
904020      10684677           310  Inter-department Transfers

        quantity_base_uom base_uom  stock_level_before_posting
904020                1.0       EA                       230.0
Sample for movement_type 943:
                  unique_key  posting_date          entry_timestamp  \
177540  2023-3355243837-0002      20230711  2023-07-11 13:41:33.000

        article_code movement_type movement_type_category  quantity_base_uom  \
177540      10137547           943                  Other               -7.0

       base_uom  stock_level_before_posting
177540       EA                        24.0
Sample for movement_type 161:
                   unique_key  posting_date          entry_timestamp  \
1055167  2023-5135036522-0002      20231229  2023-12-29 07:37:50.000

         article_code movement_type movement_type_category  quantity_base_uom  \
1055167      10809501           161         Vendor Returns               -6.0

        base_uom  stock_level_before_posting
1055167       EA                        31.0
Sample for movement_type Y51:
                  unique_key  posting_date          entry_timestamp  \
290775  2023-3360109398-0002      20230729  2023-07-30 00:33:53.000

        article_code movement_type        movement_type_category  \
290775      10147327           Y51  Depletion for Produced Goods

        quantity_base_uom base_uom  stock_level_before_posting
290775             -2.227       EA                     197.151
Sample for movement_type Y52:
                  unique_key  posting_date          entry_timestamp  \
286759  2023-3361283339-0001      20230802  2023-08-03 01:04:08.000

        article_code movement_type        movement_type_category  \
286759      10147169           Y52  Depletion for Produced Goods

        quantity_base_uom base_uom  stock_level_before_posting
286759             15.754       KG                     -15.754
Sample for movement_type 102:
                  unique_key  posting_date          entry_timestamp  \
735740  2023-5128589110-0015      20230929  2023-09-29 15:36:35.000

        article_code movement_type movement_type_category  quantity_base_uom  \
735740      10507416           102          Goods Receipt              -10.0

       base_uom  stock_level_before_posting
735740       EA                        20.0
Sample for movement_type 552:
                  unique_key  posting_date          entry_timestamp  \
288709  2024-3407026770-0001      20240111  2024-01-11 12:11:30.000

        article_code movement_type movement_type_category  quantity_base_uom  \
288709      10147186           552  Wastage and Donations                7.0

       base_uom  stock_level_before_posting
288709       EA                     249.244
Sample for movement_type 162:
                  unique_key  posting_date          entry_timestamp  \
381809  2024-5138765164-0001      20240221  2024-02-21 10:51:55.000

        article_code movement_type movement_type_category  quantity_base_uom  \
381809      10176060           162         Vendor Returns               17.0

       base_uom  stock_level_before_posting
381809       EA                        -8.0
Sample for movement_type 643:
                  unique_key  posting_date          entry_timestamp  \
531239  2024-3412476920-0001      20240130  2024-01-30 11:07:29.000

        article_code movement_type movement_type_category  quantity_base_uom  \
531239      10335895           643                  Other              -60.0

       base_uom  stock_level_before_posting
531239       EA                      2535.0

In [20]:
filtered_data = movement[movement["stock_level_before_posting"] < 0]
    
    
filtered_data

                   unique_key  posting_date          entry_timestamp  \
223      2023-3397656651-0001      20231209  2023-12-10 00:45:50.000
352      2023-3390104125-0001      20231113  2023-11-14 00:42:44.000
354      2024-3408549062-0001      20240116  2024-01-17 00:54:27.000
1056     2024-3411393426-0001      20240126  2024-01-26 23:07:20.000
1057     2024-3411442486-0001      20240126  2024-01-27 00:37:06.000
...                       ...           ...                      ...
1093398  2024-5138292157-0009      20240214  2024-02-14 13:01:05.000
1093562  2024-3414082705-0001      20240204  2024-02-05 00:41:42.000
1094389  2024-3412283140-0001      20240129  2024-01-30 00:44:27.000
1094811  2024-5139321861-0005      20240229  2024-02-29 08:09:24.000
1094964  2024-5139269437-0001      20240228  2024-02-28 12:22:02.000

         article_code movement_type movement_type_category  quantity_base_uom  \
223          10100453           701              Shrinkage                4.0
352          10100530           701              Shrinkage                1.0
354          10100530           701              Shrinkage                1.0
1056         10100950           251                  Sales               -7.0
1057         10100950           701              Shrinkage               17.0
...               ...           ...                    ...                ...
1093398      10866932           101          Goods Receipt               10.0
1093562      10866939           701              Shrinkage                1.0
1094389      10871388           701              Shrinkage                2.0
1094811      10874870           101          Goods Receipt               96.0
1094964      10879888           101          Goods Receipt               48.0

        base_uom  stock_level_before_posting
223           EA                        -1.0
352           EA                        -1.0
354           EA                        -1.0
1056          EA                        -1.0
1057          EA                        -8.0
...          ...                         ...
1093398       EA                        -3.0
1093562       EA                        -1.0
1094389       EA                        -1.0
1094811       EA                       -60.0
1094964       EA                       -19.0

[8366 rows x 9 columns]

In [21]:
filtered_data

,unique_key,posting_date,entry_timestamp,article_code,movement_type,movement_type_category,quantity_base_uom,base_uom,stock_level_before_posting
223,2023-3397656651-0001,20231209,2023-12-10 00:45:50.000,10100453,701,Shrinkage,4.0,EA,-1.0
352,2023-3390104125-0001,20231113,2023-11-14 00:42:44.000,10100530,701,Shrinkage,1.0,EA,-1.0
354,2024-3408549062-0001,20240116,2024-01-17 00:54:27.000,10100530,701,Shrinkage,1.0,EA,-1.0
1056,2024-3411393426-0001,20240126,2024-01-26 23:07:20.000,10100950,251,Sales,-7.0,EA,-1.0
1057,2024-3411442486-0001,20240126,2024-01-27 00:37:06.000,10100950,701,Shrinkage,17.0,EA,-8.0
...,...,...,...,...,...,...,...,...,...
1093398,2024-5138292157-0009,20240214,2024-02-14 13:01:05.000,10866932,101,Goods Receipt,10.0,EA,-3.0
1093562,2024-3414082705-0001,20240204,2024-02-05 00:41:42.000,10866939,701,Shrinkage,1.0,EA,-1.0
1094389,2024-3412283140-0001,20240129,2024-01-30 00:44:27.000,10871388,701,Shrinkage,2.0,EA,-1.0
1094811,2024-5139321861-0005,20240229,2024-02-29 08:09:24.000,10874870,101,Goods Receipt,96.0,EA,-60.0
1094964,2024-5139269437-0001,20240228,2024-02-28 12:22:02.000,10879888,101,Goods Receipt,48.0,EA,-19.0

In [17]:
print(movement['movement_type_category'].unique())

['Sales' 'Shrinkage' 'Goods Receipt' 'Wastage and Donations' 'Other'
 'Vendor Returns' 'Inter-department Transfers'
 'Depletion for Produced Goods']

In [21]:
print(movement.shape)
print(movement.columns)

(1094999, 10)
Index(['unique_key', 'posting_date', 'entry_timestamp', 'site_code',
       'article_code', 'movement_type', 'movement_type_category',
       'quantity_base_uom', 'base_uom', 'stock_level_before_posting'],
      dtype='object')

In [22]:
print(movement["posting_date"].min())
print(movement["posting_date"].max())

20230703
20240331

In [24]:
print(sales["date_key"].min())
print(sales["date_key"].max())

20220103
20240331

In [8]:
print(movement["site_code"].unique())
print(sales["site_code"].unique())
sales = sales.drop(columns=["site_code"])
movement = movement.drop(columns=["site_code"])

[236]
[236]

In [9]:
sales.head()

,date_key,unique_ticket_id,ticket_end_time,article_code,sales_qty_alternate_uom,alternate_uom,sales_qty_base_uom,base_uom
0,20220103,8d379521-cf90-4d83-8d8b-a2c001313b88,2022-01-03 08:02:03.000,10730757,1.0,EA,1.0,EA
1,20220103,aea5b653-2751-489e-b98c-9141d84c7018,2022-01-03 08:04:36.000,10665601,1.0,EA,1.0,EA
2,20220103,c6b2b8c8-1b52-4375-b065-79e48933fab6,2022-01-03 08:09:12.000,10164184,1.0,EA,1.0,EA
3,20220103,45bc7474-a244-4c5a-b5c1-584f8662d1f2,2022-01-03 08:09:43.000,10722932,1.0,EA,1.0,EA
4,20220103,150a9040-fb3b-4b4e-9170-17d8af09e725,2022-01-03 08:09:59.000,10143154,1.0,EA,1.0,EA

In [26]:
mask = sales["entry_timestamp"] == pd.to_datetime("20230714")
exists = mask.any()

print(f"Does the date exist in the column? {exists}")

Does the date exist in the column? False

In [29]:
sales.tail()

,date_key,site_code,unique_ticket_id,ticket_end_time,article_code,sales_qty_alternate_uom,alternate_uom,sales_qty_base_uom,base_uom
12570504,20240331,236,5375f272-6740-4e25-80f9-c3d9ef6c9e26,2024-03-31 16:14:03.000,10553501,2.0,EA,2.0,EA
12570505,20240331,236,5375f272-6740-4e25-80f9-c3d9ef6c9e26,2024-03-31 16:14:03.000,10627146,1.0,EA,1.0,EA
12570506,20240331,236,5375f272-6740-4e25-80f9-c3d9ef6c9e26,2024-03-31 16:14:03.000,10737465,1.0,EA,1.0,EA
12570507,20240331,236,5375f272-6740-4e25-80f9-c3d9ef6c9e26,2024-03-31 16:14:03.000,10768979,1.0,EA,1.0,EA
12570508,20240331,236,5375f272-6740-4e25-80f9-c3d9ef6c9e26,2024-03-31 16:14:03.000,10807062,1.0,EA,1.0,EA

In [31]:
movement.tail()

,unique_key,posting_date,entry_timestamp,site_code,article_code,movement_type,movement_type_category,quantity_base_uom,base_uom,stock_level_before_posting
1094994,2024-3429799698-0486,20240329,2024-03-29 22:23:14.000,236,10879888,251,Sales,-5.0,EA,15.0
1094995,2024-3430076530-0474,20240330,2024-03-30 23:27:54.000,236,10879888,251,Sales,-2.0,EA,10.0
1094996,2024-3430327171-0470,20240331,2024-03-31 23:00:39.000,236,10879888,251,Sales,-1.0,EA,8.0
1094997,2024-5141306929-0001,20240327,2024-03-27 13:19:10.000,236,10884830,101,Goods Receipt,36.0,EA,0.0
1094998,2024-5141306929-0002,20240327,2024-03-27 13:19:10.000,236,10885996,101,Goods Receipt,12.0,EA,0.0

In [43]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12570509 entries, 0 to 12570508
Data columns (total 9 columns):
 #   Column                   Dtype
---  ------                   -----
 0   date_key                 int64
 1   site_code                int64
 2   unique_ticket_id         object
 3   ticket_end_time          object
 4   article_code             int64
 5   sales_qty_alternate_uom  float64
 6   alternate_uom            object
 7   sales_qty_base_uom       float64
 8   base_uom                 object
dtypes: float64(2), int64(3), object(4)
memory usage: 863.1+ MB

In [51]:
sales["ticket_end_time"] = pd.to_datetime(sales["ticket_end_time"])

In [55]:
sales["ticket_end_time"].head()

0   2022-01-03 08:02:03
1   2022-01-03 08:04:36
2   2022-01-03 08:09:12
3   2022-01-03 08:09:43
4   2022-01-03 08:09:59
Name: ticket_end_time, dtype: datetime64[ns]

In [53]:
# Define the specific date you are looking for
target_date = pd.Timestamp("2024-03-31 16:14:03.000")

# Filter the DataFrame to include only rows where the date part of 'ticket_end_time' matches 'target_date'
filtered_sales = sales[sales["ticket_end_time"].dt.date == target_date]

# Display the filtered DataFrame
print(filtered_sales)

Empty DataFrame
Columns: [date_key, site_code, unique_ticket_id, ticket_end_time, article_code, sales_qty_alternate_uom, alternate_uom, sales_qty_base_uom, base_uom]
Index: []